// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gRPCStream.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GRPCStream.Protocol {
  public static partial class RpcStreamService
  {
    static readonly string __ServiceName = "gRPCStream.Protocol.RpcStreamService";

    static readonly grpc::Marshaller<global::GRPCStream.Protocol.StreamRequest> __Marshaller_gRPCStream_Protocol_StreamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCStream.Protocol.StreamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCStream.Protocol.StreamResponse> __Marshaller_gRPCStream_Protocol_StreamResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCStream.Protocol.StreamResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::GRPCStream.Protocol.StreamRequest, global::GRPCStream.Protocol.StreamResponse> __Method_GetStreamContent = new grpc::Method<global::GRPCStream.Protocol.StreamRequest, global::GRPCStream.Protocol.StreamResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GetStreamContent",
        __Marshaller_gRPCStream_Protocol_StreamRequest,
        __Marshaller_gRPCStream_Protocol_StreamResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GRPCStream.Protocol.GRPCStreamReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RpcStreamService</summary>
    [grpc::BindServiceMethod(typeof(RpcStreamService), "BindService")]
    public abstract partial class RpcStreamServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetStreamContent(grpc::IAsyncStreamReader<global::GRPCStream.Protocol.StreamRequest> requestStream, grpc::IServerStreamWriter<global::GRPCStream.Protocol.StreamResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RpcStreamService</summary>
    public partial class RpcStreamServiceClient : grpc::ClientBase<RpcStreamServiceClient>
    {
      /// <summary>Creates a new client for RpcStreamService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RpcStreamServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RpcStreamService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RpcStreamServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RpcStreamServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RpcStreamServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::GRPCStream.Protocol.StreamRequest, global::GRPCStream.Protocol.StreamResponse> GetStreamContent(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStreamContent(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::GRPCStream.Protocol.StreamRequest, global::GRPCStream.Protocol.StreamResponse> GetStreamContent(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GetStreamContent, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RpcStreamServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RpcStreamServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RpcStreamServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetStreamContent, serviceImpl.GetStreamContent).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RpcStreamServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetStreamContent, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::GRPCStream.Protocol.StreamRequest, global::GRPCStream.Protocol.StreamResponse>(serviceImpl.GetStreamContent));
    }

  }
}
#endregion
